kind: Secret
apiVersion: v1
metadata:
  name: my-vault-secret
  annotations:
    avp.kubernetes.io/path: "credentials/data/solar-system-app"
type: Opaque
stringData:
  mongousername: <mongo_username>
  mongopassword: <mongo_password>
  mongouri: <mongo_uri>
  envsecret: <env_secret>